# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qmlpinquery

# >> macros
# << macros

Summary:    QML based PIN query application using ofono-qt
Version:    0.2
Release:    1
Group:      Applications/Communications
License:    BSD
URL:        https://github.com/nemomobile/qmlpinquery
Source0:    %{name}-%{version}.tar.bz2
Source1:    qmlpinquery.service
Source100:  qmlpinquery.yaml
Requires:   qt-components-qt5
Requires:   mapplauncherd-booster-qtcomponents-qt5
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(qofono-qt5)
Provides:   meego-pinquery > 0.0.2
Obsoletes:   meego-pinquery <= 0.0.2

%description
QML PIN query dialog

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install
mkdir -p %{buildroot}%{_libdir}/systemd/user/
cp -a %{SOURCE1} %{buildroot}%{_libdir}/systemd/user/


# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/qmlpinquery
%{_usr}/share/applications/qmlpinquery.desktop
%{_libdir}/systemd/user/qmlpinquery.service
# >> files
# << files
