# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       qmlpinquery
Summary:    QML based PIN query application using ofono-qt
Version:    0.1.1
Release:    1
Group:      Applications/Communications
License:    BSD
URL:        https://github.com/nemomobile/qmlpinquery
Source0:    %{name}-%{version}.tar.bz2
Source1:    qmlpinquery.service
Source100:  qmlpinquery.yaml
Requires:   qt-components
Requires:   systemd
Requires:   systemd-user-session-targets
BuildRequires:  pkgconfig(qdeclarative-boostable)
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtDBus)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(ofono-qt)
Provides:   meego-pinquery > 0.0.2
Obsoletes:   meego-pinquery <= 0.0.2


%description
QML PIN query dialog



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install
mkdir -p %{buildroot}%{_libdir}/systemd/user/
cp -a %{SOURCE1} %{buildroot}%{_libdir}/systemd/user/


# >> install post
 # Create the qmlpinquery cache directory
mkdir -p %{buildroot}%{_libdir}/systemd/user/user-session.target.wants
ln -s ../qmlpinquery.service %{buildroot}%{_libdir}/systemd/user/user-session.target.wants/
 # << install post 


%post
# >> post
if [ "$1" -ge 1 ]; then
systemctl-user daemon-reload || :
systemctl-user restart qmlpinquery.service || :
fi
# << post 

%postun
 # >> postun
if [ "$1" -eq 0 ]; then
systemctl-user stop qmlpinquery.service || :
systemctl-user daemon-reload || :
fi
# << postun 



%files
%defattr(-,root,root,-)
%{_bindir}/qmlpinquery
%{_usr}/share/applications/qmlpinquery.desktop
%{_libdir}/systemd/user/qmlpinquery.service
# >> files
%{_libdir}/systemd/user/user-session.target.wants/qmlpinquery.service
# << files


